import type { BoardState, City, DestinationTicket, Route, TrainCard, TrainColor } from '../model/types';

export const INITIAL_TRAINS_PER_PLAYER = 45;

export const DEFAULT_CITIES: Record<string, City> = {
  atlanta: { id: 'atlanta', name: 'Atlanta' },
  boston: { id: 'boston', name: 'Boston' },
  calgary: { id: 'calgary', name: 'Calgary' },
  charleston: { id: 'charleston', name: 'Charleston' },
  chicago: { id: 'chicago', name: 'Chicago' },
  dallas: { id: 'dallas', name: 'Dallas' },
  denver: { id: 'denver', name: 'Denver' },
  duluth: { id: 'duluth', name: 'Duluth' },
  el_paso: { id: 'el_paso', name: 'El Paso' },
  helena: { id: 'helena', name: 'Helena' },
  houston: { id: 'houston', name: 'Houston' },
  kansas_city: { id: 'kansas_city', name: 'Kansas City' },
  las_vegas: { id: 'las_vegas', name: 'Las Vegas' },
  little_rock: { id: 'little_rock', name: 'Little Rock' },
  los_angeles: { id: 'los_angeles', name: 'Los Angeles' },
  miami: { id: 'miami', name: 'Miami' },
  montreal: { id: 'montreal', name: 'Montreal' },
  nashville: { id: 'nashville', name: 'Nashville' },
  new_orleans: { id: 'new_orleans', name: 'New Orleans' },
  new_york: { id: 'new_york', name: 'New York' },
  oklahoma_city: { id: 'oklahoma_city', name: 'Oklahoma City' },
  omaha: { id: 'omaha', name: 'Omaha' },
  phoenix: { id: 'phoenix', name: 'Phoenix' },
  pittsburgh: { id: 'pittsburgh', name: 'Pittsburgh' },
  portland: { id: 'portland', name: 'Portland' },
  raleigh: { id: 'raleigh', name: 'Raleigh' },
  saint_louis: { id: 'saint_louis', name: 'Saint Louis' },
  salt_lake_city: { id: 'salt_lake_city', name: 'Salt Lake City' },
  san_francisco: { id: 'san_francisco', name: 'San Francisco' },
  santa_fe: { id: 'santa_fe', name: 'Santa Fe' },
  sault_ste_marie: { id: 'sault_ste_marie', name: 'Sault Ste. Marie' },
  seattle: { id: 'seattle', name: 'Seattle' },
  toronto: { id: 'toronto', name: 'Toronto' },
  vancouver: { id: 'vancouver', name: 'Vancouver' },
  washington: { id: 'washington', name: 'Washington' },
  winnipeg: { id: 'winnipeg', name: 'Winnipeg' },
};

export const DEFAULT_ROUTES: Record<string, Route> = {
  route_atlanta_charleston_any: {
    routeId: 'route_atlanta_charleston_any',
    cityA: 'atlanta',
    cityB: 'charleston',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_atlanta_miami_blue: {
    routeId: 'route_atlanta_miami_blue',
    cityA: 'atlanta',
    cityB: 'miami',
    length: 5,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_atlanta_nashville_any: {
    routeId: 'route_atlanta_nashville_any',
    cityA: 'atlanta',
    cityB: 'nashville',
    length: 1,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_atlanta_new_orleans_yellow: {
    routeId: 'route_atlanta_new_orleans_yellow',
    cityA: 'atlanta',
    cityB: 'new_orleans',
    length: 4,
    colorRequirement: 'yellow',
    parallelRouteGroupId: 'group_atlanta_new_orleans',
    ownerPlayerId: null,
  },
  route_atlanta_new_orleans_orange: {
    routeId: 'route_atlanta_new_orleans_orange',
    cityA: 'atlanta',
    cityB: 'new_orleans',
    length: 4,
    colorRequirement: 'orange',
    parallelRouteGroupId: 'group_atlanta_new_orleans',
    ownerPlayerId: null,
  },
  route_atlanta_raleigh_any_1: {
    routeId: 'route_atlanta_raleigh_any_1',
    cityA: 'atlanta',
    cityB: 'raleigh',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_atlanta_raleigh',
    ownerPlayerId: null,
  },
  route_atlanta_raleigh_any_2: {
    routeId: 'route_atlanta_raleigh_any_2',
    cityA: 'atlanta',
    cityB: 'raleigh',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_atlanta_raleigh',
    ownerPlayerId: null,
  },
  route_boston_montreal_any_1: {
    routeId: 'route_boston_montreal_any_1',
    cityA: 'boston',
    cityB: 'montreal',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_boston_montreal',
    ownerPlayerId: null,
  },
  route_boston_montreal_any_2: {
    routeId: 'route_boston_montreal_any_2',
    cityA: 'boston',
    cityB: 'montreal',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_boston_montreal',
    ownerPlayerId: null,
  },
  route_boston_new_york_yellow: {
    routeId: 'route_boston_new_york_yellow',
    cityA: 'boston',
    cityB: 'new_york',
    length: 2,
    colorRequirement: 'yellow',
    parallelRouteGroupId: 'group_boston_new_york',
    ownerPlayerId: null,
  },
  route_boston_new_york_red: {
    routeId: 'route_boston_new_york_red',
    cityA: 'boston',
    cityB: 'new_york',
    length: 2,
    colorRequirement: 'red',
    parallelRouteGroupId: 'group_boston_new_york',
    ownerPlayerId: null,
  },
  route_calgary_helena_any: {
    routeId: 'route_calgary_helena_any',
    cityA: 'calgary',
    cityB: 'helena',
    length: 4,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_calgary_seattle_any: {
    routeId: 'route_calgary_seattle_any',
    cityA: 'calgary',
    cityB: 'seattle',
    length: 4,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_calgary_vancouver_any: {
    routeId: 'route_calgary_vancouver_any',
    cityA: 'calgary',
    cityB: 'vancouver',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_calgary_winnipeg_white: {
    routeId: 'route_calgary_winnipeg_white',
    cityA: 'calgary',
    cityB: 'winnipeg',
    length: 6,
    colorRequirement: 'white',
    ownerPlayerId: null,
  },
  route_charleston_miami_purple: {
    routeId: 'route_charleston_miami_purple',
    cityA: 'charleston',
    cityB: 'miami',
    length: 4,
    colorRequirement: 'purple',
    ownerPlayerId: null,
  },
  route_charleston_raleigh_any: {
    routeId: 'route_charleston_raleigh_any',
    cityA: 'charleston',
    cityB: 'raleigh',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_chicago_duluth_red: {
    routeId: 'route_chicago_duluth_red',
    cityA: 'chicago',
    cityB: 'duluth',
    length: 3,
    colorRequirement: 'red',
    ownerPlayerId: null,
  },
  route_chicago_kansas_city_blue: {
    routeId: 'route_chicago_kansas_city_blue',
    cityA: 'chicago',
    cityB: 'kansas_city',
    length: 2,
    colorRequirement: 'blue',
    parallelRouteGroupId: 'group_chicago_kansas_city',
    ownerPlayerId: null,
  },
  route_chicago_kansas_city_white: {
    routeId: 'route_chicago_kansas_city_white',
    cityA: 'chicago',
    cityB: 'kansas_city',
    length: 2,
    colorRequirement: 'white',
    parallelRouteGroupId: 'group_chicago_kansas_city',
    ownerPlayerId: null,
  },
  route_chicago_omaha_blue: {
    routeId: 'route_chicago_omaha_blue',
    cityA: 'chicago',
    cityB: 'omaha',
    length: 4,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_chicago_pittsburgh_orange: {
    routeId: 'route_chicago_pittsburgh_orange',
    cityA: 'chicago',
    cityB: 'pittsburgh',
    length: 3,
    colorRequirement: 'orange',
    parallelRouteGroupId: 'group_chicago_pittsburgh',
    ownerPlayerId: null,
  },
  route_chicago_pittsburgh_black: {
    routeId: 'route_chicago_pittsburgh_black',
    cityA: 'chicago',
    cityB: 'pittsburgh',
    length: 3,
    colorRequirement: 'black',
    parallelRouteGroupId: 'group_chicago_pittsburgh',
    ownerPlayerId: null,
  },
  route_chicago_saint_louis_green: {
    routeId: 'route_chicago_saint_louis_green',
    cityA: 'chicago',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'green',
    parallelRouteGroupId: 'group_chicago_saint_louis',
    ownerPlayerId: null,
  },
  route_chicago_saint_louis_white: {
    routeId: 'route_chicago_saint_louis_white',
    cityA: 'chicago',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'white',
    parallelRouteGroupId: 'group_chicago_saint_louis',
    ownerPlayerId: null,
  },
  route_chicago_toronto_white: {
    routeId: 'route_chicago_toronto_white',
    cityA: 'chicago',
    cityB: 'toronto',
    length: 4,
    colorRequirement: 'white',
    ownerPlayerId: null,
  },
  route_dallas_el_paso_red: {
    routeId: 'route_dallas_el_paso_red',
    cityA: 'dallas',
    cityB: 'el_paso',
    length: 4,
    colorRequirement: 'red',
    ownerPlayerId: null,
  },
  route_dallas_houston_any_1: {
    routeId: 'route_dallas_houston_any_1',
    cityA: 'dallas',
    cityB: 'houston',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_dallas_houston',
    ownerPlayerId: null,
  },
  route_dallas_houston_any_2: {
    routeId: 'route_dallas_houston_any_2',
    cityA: 'dallas',
    cityB: 'houston',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_dallas_houston',
    ownerPlayerId: null,
  },
  route_dallas_little_rock_any: {
    routeId: 'route_dallas_little_rock_any',
    cityA: 'dallas',
    cityB: 'little_rock',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_dallas_oklahoma_city_any_1: {
    routeId: 'route_dallas_oklahoma_city_any_1',
    cityA: 'dallas',
    cityB: 'oklahoma_city',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_dallas_oklahoma_city',
    ownerPlayerId: null,
  },
  route_dallas_oklahoma_city_any_2: {
    routeId: 'route_dallas_oklahoma_city_any_2',
    cityA: 'dallas',
    cityB: 'oklahoma_city',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_dallas_oklahoma_city',
    ownerPlayerId: null,
  },
  route_denver_helena_green: {
    routeId: 'route_denver_helena_green',
    cityA: 'denver',
    cityB: 'helena',
    length: 4,
    colorRequirement: 'green',
    ownerPlayerId: null,
  },
  route_denver_kansas_city_black: {
    routeId: 'route_denver_kansas_city_black',
    cityA: 'denver',
    cityB: 'kansas_city',
    length: 4,
    colorRequirement: 'black',
    parallelRouteGroupId: 'group_denver_kansas_city',
    ownerPlayerId: null,
  },
  route_denver_kansas_city_orange: {
    routeId: 'route_denver_kansas_city_orange',
    cityA: 'denver',
    cityB: 'kansas_city',
    length: 4,
    colorRequirement: 'orange',
    parallelRouteGroupId: 'group_denver_kansas_city',
    ownerPlayerId: null,
  },
  route_denver_oklahoma_city_red: {
    routeId: 'route_denver_oklahoma_city_red',
    cityA: 'denver',
    cityB: 'oklahoma_city',
    length: 4,
    colorRequirement: 'red',
    ownerPlayerId: null,
  },
  route_denver_omaha_purple: {
    routeId: 'route_denver_omaha_purple',
    cityA: 'denver',
    cityB: 'omaha',
    length: 4,
    colorRequirement: 'purple',
    ownerPlayerId: null,
  },
  route_denver_phoenix_white: {
    routeId: 'route_denver_phoenix_white',
    cityA: 'denver',
    cityB: 'phoenix',
    length: 6,
    colorRequirement: 'white',
    ownerPlayerId: null,
  },
  route_denver_salt_lake_city_red: {
    routeId: 'route_denver_salt_lake_city_red',
    cityA: 'denver',
    cityB: 'salt_lake_city',
    length: 3,
    colorRequirement: 'red',
    parallelRouteGroupId: 'group_denver_salt_lake_city',
    ownerPlayerId: null,
  },
  route_denver_salt_lake_city_yellow: {
    routeId: 'route_denver_salt_lake_city_yellow',
    cityA: 'denver',
    cityB: 'salt_lake_city',
    length: 3,
    colorRequirement: 'yellow',
    parallelRouteGroupId: 'group_denver_salt_lake_city',
    ownerPlayerId: null,
  },
  route_denver_santa_fe_any: {
    routeId: 'route_denver_santa_fe_any',
    cityA: 'denver',
    cityB: 'santa_fe',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_duluth_helena_orange: {
    routeId: 'route_duluth_helena_orange',
    cityA: 'duluth',
    cityB: 'helena',
    length: 6,
    colorRequirement: 'orange',
    ownerPlayerId: null,
  },
  route_duluth_omaha_any_1: {
    routeId: 'route_duluth_omaha_any_1',
    cityA: 'duluth',
    cityB: 'omaha',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_duluth_omaha',
    ownerPlayerId: null,
  },
  route_duluth_omaha_any_2: {
    routeId: 'route_duluth_omaha_any_2',
    cityA: 'duluth',
    cityB: 'omaha',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_duluth_omaha',
    ownerPlayerId: null,
  },
  route_duluth_sault_ste_marie_any: {
    routeId: 'route_duluth_sault_ste_marie_any',
    cityA: 'duluth',
    cityB: 'sault_ste_marie',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_duluth_toronto_purple: {
    routeId: 'route_duluth_toronto_purple',
    cityA: 'duluth',
    cityB: 'toronto',
    length: 6,
    colorRequirement: 'purple',
    ownerPlayerId: null,
  },
  route_duluth_winnipeg_black: {
    routeId: 'route_duluth_winnipeg_black',
    cityA: 'duluth',
    cityB: 'winnipeg',
    length: 4,
    colorRequirement: 'black',
    ownerPlayerId: null,
  },
  route_el_paso_houston_green: {
    routeId: 'route_el_paso_houston_green',
    cityA: 'el_paso',
    cityB: 'houston',
    length: 6,
    colorRequirement: 'green',
    ownerPlayerId: null,
  },
  route_el_paso_los_angeles_black: {
    routeId: 'route_el_paso_los_angeles_black',
    cityA: 'el_paso',
    cityB: 'los_angeles',
    length: 6,
    colorRequirement: 'black',
    ownerPlayerId: null,
  },
  route_el_paso_oklahoma_city_yellow: {
    routeId: 'route_el_paso_oklahoma_city_yellow',
    cityA: 'el_paso',
    cityB: 'oklahoma_city',
    length: 5,
    colorRequirement: 'yellow',
    ownerPlayerId: null,
  },
  route_el_paso_phoenix_any: {
    routeId: 'route_el_paso_phoenix_any',
    cityA: 'el_paso',
    cityB: 'phoenix',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_el_paso_santa_fe_any: {
    routeId: 'route_el_paso_santa_fe_any',
    cityA: 'el_paso',
    cityB: 'santa_fe',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_helena_omaha_red: {
    routeId: 'route_helena_omaha_red',
    cityA: 'helena',
    cityB: 'omaha',
    length: 5,
    colorRequirement: 'red',
    ownerPlayerId: null,
  },
  route_helena_salt_lake_city_purple: {
    routeId: 'route_helena_salt_lake_city_purple',
    cityA: 'helena',
    cityB: 'salt_lake_city',
    length: 3,
    colorRequirement: 'purple',
    ownerPlayerId: null,
  },
  route_helena_seattle_yellow: {
    routeId: 'route_helena_seattle_yellow',
    cityA: 'helena',
    cityB: 'seattle',
    length: 6,
    colorRequirement: 'yellow',
    ownerPlayerId: null,
  },
  route_helena_winnipeg_blue: {
    routeId: 'route_helena_winnipeg_blue',
    cityA: 'helena',
    cityB: 'winnipeg',
    length: 4,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_houston_new_orleans_any: {
    routeId: 'route_houston_new_orleans_any',
    cityA: 'houston',
    cityB: 'new_orleans',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_kansas_city_oklahoma_city_any_1: {
    routeId: 'route_kansas_city_oklahoma_city_any_1',
    cityA: 'kansas_city',
    cityB: 'oklahoma_city',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_kansas_city_oklahoma_city',
    ownerPlayerId: null,
  },
  route_kansas_city_oklahoma_city_any_2: {
    routeId: 'route_kansas_city_oklahoma_city_any_2',
    cityA: 'kansas_city',
    cityB: 'oklahoma_city',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_kansas_city_oklahoma_city',
    ownerPlayerId: null,
  },
  route_kansas_city_omaha_any_1: {
    routeId: 'route_kansas_city_omaha_any_1',
    cityA: 'kansas_city',
    cityB: 'omaha',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_kansas_city_omaha',
    ownerPlayerId: null,
  },
  route_kansas_city_omaha_any_2: {
    routeId: 'route_kansas_city_omaha_any_2',
    cityA: 'kansas_city',
    cityB: 'omaha',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_kansas_city_omaha',
    ownerPlayerId: null,
  },
  route_kansas_city_saint_louis_blue: {
    routeId: 'route_kansas_city_saint_louis_blue',
    cityA: 'kansas_city',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'blue',
    parallelRouteGroupId: 'group_kansas_city_saint_louis',
    ownerPlayerId: null,
  },
  route_kansas_city_saint_louis_purple: {
    routeId: 'route_kansas_city_saint_louis_purple',
    cityA: 'kansas_city',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'purple',
    parallelRouteGroupId: 'group_kansas_city_saint_louis',
    ownerPlayerId: null,
  },
  route_las_vegas_los_angeles_any: {
    routeId: 'route_las_vegas_los_angeles_any',
    cityA: 'las_vegas',
    cityB: 'los_angeles',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_las_vegas_salt_lake_city_orange: {
    routeId: 'route_las_vegas_salt_lake_city_orange',
    cityA: 'las_vegas',
    cityB: 'salt_lake_city',
    length: 3,
    colorRequirement: 'orange',
    ownerPlayerId: null,
  },
  route_little_rock_nashville_white: {
    routeId: 'route_little_rock_nashville_white',
    cityA: 'little_rock',
    cityB: 'nashville',
    length: 3,
    colorRequirement: 'white',
    ownerPlayerId: null,
  },
  route_little_rock_new_orleans_green: {
    routeId: 'route_little_rock_new_orleans_green',
    cityA: 'little_rock',
    cityB: 'new_orleans',
    length: 3,
    colorRequirement: 'green',
    ownerPlayerId: null,
  },
  route_little_rock_oklahoma_city_any: {
    routeId: 'route_little_rock_oklahoma_city_any',
    cityA: 'little_rock',
    cityB: 'oklahoma_city',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_little_rock_saint_louis_any: {
    routeId: 'route_little_rock_saint_louis_any',
    cityA: 'little_rock',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_los_angeles_phoenix_any: {
    routeId: 'route_los_angeles_phoenix_any',
    cityA: 'los_angeles',
    cityB: 'phoenix',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_los_angeles_san_francisco_yellow: {
    routeId: 'route_los_angeles_san_francisco_yellow',
    cityA: 'los_angeles',
    cityB: 'san_francisco',
    length: 3,
    colorRequirement: 'yellow',
    parallelRouteGroupId: 'group_los_angeles_san_francisco',
    ownerPlayerId: null,
  },
  route_los_angeles_san_francisco_purple: {
    routeId: 'route_los_angeles_san_francisco_purple',
    cityA: 'los_angeles',
    cityB: 'san_francisco',
    length: 3,
    colorRequirement: 'purple',
    parallelRouteGroupId: 'group_los_angeles_san_francisco',
    ownerPlayerId: null,
  },
  route_miami_new_orleans_red: {
    routeId: 'route_miami_new_orleans_red',
    cityA: 'miami',
    cityB: 'new_orleans',
    length: 6,
    colorRequirement: 'red',
    ownerPlayerId: null,
  },
  route_montreal_new_york_blue: {
    routeId: 'route_montreal_new_york_blue',
    cityA: 'montreal',
    cityB: 'new_york',
    length: 3,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_montreal_sault_ste_marie_black: {
    routeId: 'route_montreal_sault_ste_marie_black',
    cityA: 'montreal',
    cityB: 'sault_ste_marie',
    length: 5,
    colorRequirement: 'black',
    ownerPlayerId: null,
  },
  route_montreal_toronto_any: {
    routeId: 'route_montreal_toronto_any',
    cityA: 'montreal',
    cityB: 'toronto',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_nashville_pittsburgh_yellow: {
    routeId: 'route_nashville_pittsburgh_yellow',
    cityA: 'nashville',
    cityB: 'pittsburgh',
    length: 4,
    colorRequirement: 'yellow',
    ownerPlayerId: null,
  },
  route_nashville_raleigh_black: {
    routeId: 'route_nashville_raleigh_black',
    cityA: 'nashville',
    cityB: 'raleigh',
    length: 3,
    colorRequirement: 'black',
    ownerPlayerId: null,
  },
  route_nashville_saint_louis_any: {
    routeId: 'route_nashville_saint_louis_any',
    cityA: 'nashville',
    cityB: 'saint_louis',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_new_york_pittsburgh_white: {
    routeId: 'route_new_york_pittsburgh_white',
    cityA: 'new_york',
    cityB: 'pittsburgh',
    length: 2,
    colorRequirement: 'white',
    parallelRouteGroupId: 'group_new_york_pittsburgh',
    ownerPlayerId: null,
  },
  route_new_york_pittsburgh_green: {
    routeId: 'route_new_york_pittsburgh_green',
    cityA: 'new_york',
    cityB: 'pittsburgh',
    length: 2,
    colorRequirement: 'green',
    parallelRouteGroupId: 'group_new_york_pittsburgh',
    ownerPlayerId: null,
  },
  route_new_york_washington_orange: {
    routeId: 'route_new_york_washington_orange',
    cityA: 'new_york',
    cityB: 'washington',
    length: 2,
    colorRequirement: 'orange',
    parallelRouteGroupId: 'group_new_york_washington',
    ownerPlayerId: null,
  },
  route_new_york_washington_black: {
    routeId: 'route_new_york_washington_black',
    cityA: 'new_york',
    cityB: 'washington',
    length: 2,
    colorRequirement: 'black',
    parallelRouteGroupId: 'group_new_york_washington',
    ownerPlayerId: null,
  },
  route_oklahoma_city_santa_fe_blue: {
    routeId: 'route_oklahoma_city_santa_fe_blue',
    cityA: 'oklahoma_city',
    cityB: 'santa_fe',
    length: 3,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_phoenix_santa_fe_any: {
    routeId: 'route_phoenix_santa_fe_any',
    cityA: 'phoenix',
    cityB: 'santa_fe',
    length: 3,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_pittsburgh_raleigh_any: {
    routeId: 'route_pittsburgh_raleigh_any',
    cityA: 'pittsburgh',
    cityB: 'raleigh',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_pittsburgh_saint_louis_green: {
    routeId: 'route_pittsburgh_saint_louis_green',
    cityA: 'pittsburgh',
    cityB: 'saint_louis',
    length: 5,
    colorRequirement: 'green',
    ownerPlayerId: null,
  },
  route_pittsburgh_toronto_any: {
    routeId: 'route_pittsburgh_toronto_any',
    cityA: 'pittsburgh',
    cityB: 'toronto',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_pittsburgh_washington_any: {
    routeId: 'route_pittsburgh_washington_any',
    cityA: 'pittsburgh',
    cityB: 'washington',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_portland_salt_lake_city_blue: {
    routeId: 'route_portland_salt_lake_city_blue',
    cityA: 'portland',
    cityB: 'salt_lake_city',
    length: 6,
    colorRequirement: 'blue',
    ownerPlayerId: null,
  },
  route_portland_san_francisco_green: {
    routeId: 'route_portland_san_francisco_green',
    cityA: 'portland',
    cityB: 'san_francisco',
    length: 5,
    colorRequirement: 'green',
    parallelRouteGroupId: 'group_portland_san_francisco',
    ownerPlayerId: null,
  },
  route_portland_san_francisco_purple: {
    routeId: 'route_portland_san_francisco_purple',
    cityA: 'portland',
    cityB: 'san_francisco',
    length: 5,
    colorRequirement: 'purple',
    parallelRouteGroupId: 'group_portland_san_francisco',
    ownerPlayerId: null,
  },
  route_portland_seattle_any_1: {
    routeId: 'route_portland_seattle_any_1',
    cityA: 'portland',
    cityB: 'seattle',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_portland_seattle',
    ownerPlayerId: null,
  },
  route_portland_seattle_any_2: {
    routeId: 'route_portland_seattle_any_2',
    cityA: 'portland',
    cityB: 'seattle',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_portland_seattle',
    ownerPlayerId: null,
  },
  route_raleigh_washington_any_1: {
    routeId: 'route_raleigh_washington_any_1',
    cityA: 'raleigh',
    cityB: 'washington',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_raleigh_washington',
    ownerPlayerId: null,
  },
  route_raleigh_washington_any_2: {
    routeId: 'route_raleigh_washington_any_2',
    cityA: 'raleigh',
    cityB: 'washington',
    length: 2,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_raleigh_washington',
    ownerPlayerId: null,
  },
  route_salt_lake_city_san_francisco_orange: {
    routeId: 'route_salt_lake_city_san_francisco_orange',
    cityA: 'salt_lake_city',
    cityB: 'san_francisco',
    length: 5,
    colorRequirement: 'orange',
    parallelRouteGroupId: 'group_salt_lake_city_san_francisco',
    ownerPlayerId: null,
  },
  route_salt_lake_city_san_francisco_white: {
    routeId: 'route_salt_lake_city_san_francisco_white',
    cityA: 'salt_lake_city',
    cityB: 'san_francisco',
    length: 5,
    colorRequirement: 'white',
    parallelRouteGroupId: 'group_salt_lake_city_san_francisco',
    ownerPlayerId: null,
  },
  route_sault_ste_marie_toronto_any: {
    routeId: 'route_sault_ste_marie_toronto_any',
    cityA: 'sault_ste_marie',
    cityB: 'toronto',
    length: 2,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_sault_ste_marie_winnipeg_any: {
    routeId: 'route_sault_ste_marie_winnipeg_any',
    cityA: 'sault_ste_marie',
    cityB: 'winnipeg',
    length: 6,
    colorRequirement: 'any',
    ownerPlayerId: null,
  },
  route_seattle_vancouver_any_1: {
    routeId: 'route_seattle_vancouver_any_1',
    cityA: 'seattle',
    cityB: 'vancouver',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_seattle_vancouver',
    ownerPlayerId: null,
  },
  route_seattle_vancouver_any_2: {
    routeId: 'route_seattle_vancouver_any_2',
    cityA: 'seattle',
    cityB: 'vancouver',
    length: 1,
    colorRequirement: 'any',
    parallelRouteGroupId: 'group_seattle_vancouver',
    ownerPlayerId: null,
  },
};


export function createInitialBoard(): BoardState {
  return {
    cities: { ...DEFAULT_CITIES },
    routes: JSON.parse(JSON.stringify(DEFAULT_ROUTES)),
  };
}

export function createSampleTrainDeck(): TrainCard[] {
  const colors: TrainColor[] = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'black', 'white'];
  const deck: TrainCard[] = [];
  let cardId = 1;

  for (const color of colors) {
    for (let i = 0; i < 12; i++) {
      deck.push({ id: `card_${cardId++}`, color });
    }
  }

  // Locomotives / Wild cards
  for (let i = 0; i < 14; i++) {
    deck.push({ id: `card_${cardId++}`, color: 'locomotive' });
  }

  return deck;
}

export function createSampleDestinationDeck(): DestinationTicket[] {
  return [
    { id: 'ticket_1', cityA: 'los_angeles', cityB: 'new_york', points: 21 },
    { id: 'ticket_2', cityA: 'duluth', cityB: 'houston', points: 8 },
    { id: 'ticket_3', cityA: 'sault_ste_marie', cityB: 'nashville', points: 8 },
    { id: 'ticket_4', cityA: 'new_york', cityB: 'atlanta', points: 6 },
    { id: 'ticket_5', cityA: 'portland', cityB: 'phoenix', points: 11 },
    { id: 'ticket_6', cityA: 'vancouver', cityB: 'montreal', points: 20 },
    { id: 'ticket_7', cityA: 'duluth', cityB: 'el_paso', points: 10 },
    { id: 'ticket_8', cityA: 'toronto', cityB: 'miami', points: 10 },
    { id: 'ticket_9', cityA: 'portland', cityB: 'nashville', points: 17 },
    { id: 'ticket_10', cityA: 'san_francisco', cityB: 'atlanta', points: 17 },
  ];
}

export const ROUTE_LENGTH_POINTS: Record<number, number> = {
  1: 1,
  2: 2,
  3: 4,
  4: 7,
  5: 10,
  6: 15,
};

export function getPointsForRouteLength(length: number): number {
  return ROUTE_LENGTH_POINTS[length] ?? length * 2;
}
